version: '3'

services:
  flask-app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8081
    volumes:
      - .:/app
    restart: always